// Code generated by mockery. DO NOT EDIT.

//go:build test

package mocks

import (
	context "context"

	config "github.com/outcatcher/hipapu/internal/config"

	mock "github.com/stretchr/testify/mock"
)

// Mockapplication is an autogenerated mock type for the application type
type Mockapplication struct {
	mock.Mock
}

type Mockapplication_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockapplication) EXPECT() *Mockapplication_Expecter {
	return &Mockapplication_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: remoteURL, localPath
func (_m *Mockapplication) Add(remoteURL string, localPath string) error {
	ret := _m.Called(remoteURL, localPath)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(remoteURL, localPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockapplication_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Mockapplication_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - remoteURL string
//   - localPath string
func (_e *Mockapplication_Expecter) Add(remoteURL interface{}, localPath interface{}) *Mockapplication_Add_Call {
	return &Mockapplication_Add_Call{Call: _e.mock.On("Add", remoteURL, localPath)}
}

func (_c *Mockapplication_Add_Call) Run(run func(remoteURL string, localPath string)) *Mockapplication_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Mockapplication_Add_Call) Return(_a0 error) *Mockapplication_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockapplication_Add_Call) RunAndReturn(run func(string, string) error) *Mockapplication_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *Mockapplication) List() []config.Installation {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []config.Installation
	if rf, ok := ret.Get(0).(func() []config.Installation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Installation)
		}
	}

	return r0
}

// Mockapplication_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Mockapplication_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *Mockapplication_Expecter) List() *Mockapplication_List_Call {
	return &Mockapplication_List_Call{Call: _e.mock.On("List")}
}

func (_c *Mockapplication_List_Call) Run(run func()) *Mockapplication_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mockapplication_List_Call) Return(_a0 []config.Installation) *Mockapplication_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockapplication_List_Call) RunAndReturn(run func() []config.Installation) *Mockapplication_List_Call {
	_c.Call.Return(run)
	return _c
}

// Synchronize provides a mock function with given fields: ctx
func (_m *Mockapplication) Synchronize(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Synchronize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockapplication_Synchronize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Synchronize'
type Mockapplication_Synchronize_Call struct {
	*mock.Call
}

// Synchronize is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Mockapplication_Expecter) Synchronize(ctx interface{}) *Mockapplication_Synchronize_Call {
	return &Mockapplication_Synchronize_Call{Call: _e.mock.On("Synchronize", ctx)}
}

func (_c *Mockapplication_Synchronize_Call) Run(run func(ctx context.Context)) *Mockapplication_Synchronize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Mockapplication_Synchronize_Call) Return(_a0 error) *Mockapplication_Synchronize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockapplication_Synchronize_Call) RunAndReturn(run func(context.Context) error) *Mockapplication_Synchronize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockapplication creates a new instance of Mockapplication. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockapplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockapplication {
	mock := &Mockapplication{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
