version: "3"

dotenv:
  - .env

tasks:
  default:
    silent: true
    cmd: task --list

  lint:
    desc: Run lint on the project
    cmd: docker run -t --rm -v $(pwd):/app -w /app golangci/golangci-lint:v2.0.2 golangci-lint run

  generate:
    desc: Generates mocks
    cmd: docker run -v "$PWD":/src -w /src vektra/mockery:v2.53

  test:
    desc: Run tests
    silent: true
    cmds:
      - go test -v --tags=test -cover -covermode atomic -coverpkg=./... -coverprofile=coverage.out -count=1 ./...
      - grep -v -E -f .covignore coverage.out > coverage.filtered.out
      - mv coverage.filtered.out coverage.out
      - go tool cover -func=coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  build:
    desc: Build binary
    cmd: CGO_ENABLED=0 go build -ldflags='-s -w' -o ./build/hipapu ./cmd/main.go

  install:
    desc: Build and install to ~/.local/bin
    deps:
      - task: build
    vars:
      home:
        sh: echo ~
    cmds:
      - cp "./build/hipapu" "{{.home}}/.local/bin/hipapu"