// Code generated by mockery. DO NOT EDIT.

//go:build test

package mocks

import (
	lock "github.com/outcatcher/hipapu/internal/lock"
	mock "github.com/stretchr/testify/mock"
)

// MockinstallationsLock is an autogenerated mock type for the installationsLock type
type MockinstallationsLock struct {
	mock.Mock
}

type MockinstallationsLock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockinstallationsLock) EXPECT() *MockinstallationsLock_Expecter {
	return &MockinstallationsLock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: installation
func (_m *MockinstallationsLock) Add(installation lock.Installation) error {
	ret := _m.Called(installation)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(lock.Installation) error); ok {
		r0 = rf(installation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockinstallationsLock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockinstallationsLock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - installation lock.Installation
func (_e *MockinstallationsLock_Expecter) Add(installation interface{}) *MockinstallationsLock_Add_Call {
	return &MockinstallationsLock_Add_Call{Call: _e.mock.On("Add", installation)}
}

func (_c *MockinstallationsLock_Add_Call) Run(run func(installation lock.Installation)) *MockinstallationsLock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(lock.Installation))
	})
	return _c
}

func (_c *MockinstallationsLock_Add_Call) Return(_a0 error) *MockinstallationsLock_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockinstallationsLock_Add_Call) RunAndReturn(run func(lock.Installation) error) *MockinstallationsLock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstallations provides a mock function with no fields
func (_m *MockinstallationsLock) GetInstallations() []lock.Installation {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInstallations")
	}

	var r0 []lock.Installation
	if rf, ok := ret.Get(0).(func() []lock.Installation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lock.Installation)
		}
	}

	return r0
}

// MockinstallationsLock_GetInstallations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstallations'
type MockinstallationsLock_GetInstallations_Call struct {
	*mock.Call
}

// GetInstallations is a helper method to define mock.On call
func (_e *MockinstallationsLock_Expecter) GetInstallations() *MockinstallationsLock_GetInstallations_Call {
	return &MockinstallationsLock_GetInstallations_Call{Call: _e.mock.On("GetInstallations")}
}

func (_c *MockinstallationsLock_GetInstallations_Call) Run(run func()) *MockinstallationsLock_GetInstallations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockinstallationsLock_GetInstallations_Call) Return(_a0 []lock.Installation) *MockinstallationsLock_GetInstallations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockinstallationsLock_GetInstallations_Call) RunAndReturn(run func() []lock.Installation) *MockinstallationsLock_GetInstallations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockinstallationsLock creates a new instance of MockinstallationsLock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockinstallationsLock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockinstallationsLock {
	mock := &MockinstallationsLock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
